export const COLORS = [
  null,
  { tone: 6, brightness: 3 },
  { tone: 6, brightness: 2 },
  { tone: 1, brightness: 3 },
  { tone: 3, brightness: 3 },
  { tone: 4, brightness: 4 },
  { tone: 3, brightness: 4 },
  { tone: 2, brightness: 3 },
  { tone: 5, brightness: 4 },
  { tone: 4, brightness: 3 },
  { tone: 1, brightness: 2 },
  { tone: 5, brightness: 2 },
  { tone: 4, brightness: 2 },
  { tone: 5, brightness: 1 },
  { tone: 1, brightness: 1 },
  { tone: 2, brightness: 0 },
  { tone: 0, brightness: 0 },
  { tone: 1, brightness: 0 },
  { tone: 5, brightness: 0 },
  { tone: 4, brightness: 1 },
  { tone: 5, brightness: 3 },
  { tone: 3, brightness: 0 },
  { tone: 4, brightness: 0 },
  { tone: 6, brightness: 0 },
  { tone: 2, brightness: 1 },
  { tone: 3, brightness: 1 },
  { tone: 6, brightness: 1 },
  { tone: 0, brightness: 1 },
  { tone: 2, brightness: 2 },
  { tone: 3, brightness: 2 },
  { tone: 0, brightness: 2 },
  { tone: 0, brightness: 3 },
  { tone: 1, brightness: 4 },
  { tone: 2, brightness: 4 },
  { tone: 6, brightness: 4 },
  { tone: 0, brightness: 4 },
];
